### ISSUE TITLE
Выбрать базовые шаблоны для реализации фронтенда (не админка)

### ISSUE THREAD

**Issue by p-p-m** [StoreInBox/sib-main#1]
Основные требования 
- нейтральные цвета (серый + пару основных цветов которые было б легко менять)
- светлый фон (для темного будет когда то потом)
- "легкий" интерфейс, много пространства, флетовый дизайн

**Comment by p-p-m** [comment]
вот шаблон который мне понравился их предложены на prom.ua: https://my.prom.ua/cabinet/design-template-preview/527

**Comment by terpiljenya** [comment]
+1, мне еще нравиться https://my.prom.ua/cabinet/design-template-preview/594

**Comment by terpiljenya** [comment]
предлагаю сюда также кидать ссылки на удачные реализации отдельных элементов сайта (элементы дизайна, анимации, галереи и т.д.)

**Comment by p-p-m** [comment]
Я правильно понимаю что шаблон уже выбран окончательно?
(Можно этот тикет закрывать?)
