### ISSUE TITLE
Создать шаблон для главной страницы сайта

### ISSUE THREAD

**Issue by p-p-m** [StoreInBox/sib-main#2]
Путь к шаблону `sib-main/main/assembly/templates/home/home.html`

Документация к старнице: http://zymud.pythonanywhere.com/docs/pages/home_page.html

Из переменных - пока что есть только категории. Если нужно чтото еще - пиши.

**Comment by terpiljenya** [comment]
Дока как бы не особо информативна), совсем не понятно куда класть статику? как наследовать шаблоны? есть ли хот релоад (но это не обязательно) ? 

И важный момент - лучше что б все таки было две папки шаблонов - 1) твои самодокументированы и я их трогать не буду 2) те которые создаю я

**Comment by p-p-m** [comment]
> И важный момент - лучше что б все таки было две папки шаблонов - 1) твои самодокументированы и я их трогать не буду 2) те которые создаю я

шаблоны класть в `sib-main/main/assembly/templates/`. Собственно говоря тебе нужно заменить мой шаблон на свой. Можешь мой просто переименовать в home.html.example например ну или создать в папке `templates` папочку examples и туда перекладывать мои.

> совсем не понятно куда класть статику? 

Со статикой меня устраивает подход предидущего проекта, в котором есть 3 папки:
1. `assets` - папка где лежит нескомпилированая статика, которая разрабатывается.
2. `static` - папка куда `grunt` или ктото-другой складывает скомпилированую и сжатую статику с `assets` и установленых модулей.
3. `collected_static` - папочка куда джанго собирает всю статику с `static` и со всех джанго-модулей, которая и будеи сервится на продакшене.

> как наследовать шаблоны?

Не совсем понял вопроса. Но как я понимаю django-way должен пожходить {% extend 'base.html' %} и т.д.

> есть ли хот релоад (но это не обязательно) ? 

Ну grunt watch будет релоадить статику в папке `static` и она автоматически будет подтягиватся при включенном дебаг-моде. Джанго шаблоны по-моему тоже будут братся новые при перезагрзке страницы, но это нужно перепроверить

**Comment by terpiljenya** [comment]
1) Нужна в доке ссылка на доку по джанго шаблонах) 
2) Там сейчас другой путь к шаблонам!, хочу что б был четкий работающий пример с папкой  `static` + отдельно так и были шаблоны-доки
3) В идеале, как я говорил, должна быть одна папка для фронта

**Comment by p-p-m** [comment]
я завтра все сделаю, посмотришь вечером

**Comment by p-p-m** [comment]
сделал. Общее описание тут:
https://github.com/StoreInBox/sib-main/tree/master/frontend

От себя еще добавлю, что грунт файл я просто скопировал с предидущего проект и его надо бы правильно отконфигурировать. Также обрати внимание на пример наследования в templates-examples и на то что если файл home.html удалить из templates то будет показываться он же из templates-examples
